### ISSUE TITLE
Fehlende Datei

### ISSUE THREAD

**Issue by woergl** [Pictureclass/ALTIS-LIFE-CONTROL#1]
die datei "include/player_list.inc.php" fehlt im ordner include, sie wird in der player_list.php aufgerufen

**Comment by Pictureclass** [comment]
Meinst du die Datei? https://github.com/Pictureclass/ALTIS-LIFE-CONTROL/blob/master/admin/include/player_list.inc.php

**Comment by woergl** [comment]
Ja, ich hab im falschen Ordner geschaut :/  tut mir leid für die umstände

**Comment by Pictureclass** [comment]
Super das es da ist. Hatte ja einen leichten Schweisaubruch. Wenn was ist, einfach melden
