### ISSUE TITLE
Wenn man einen User editieren möchte

### ISSUE THREAD

**Issue by myperx** [Pictureclass/ALTIS-LIFE-CONTROL#2]
"fehler: Table 'altislifetest.wanted' doesn't exist"

**Comment by Pictureclass** [comment]
Danke. Schau ich mir an. Kannst du einen sql drump mir zur Verfügung stellen?

**Comment by Pictureclass** [comment]
Und die URL der Seite, wo es auftritt.

**Comment by myperx** [comment]
URL: /admin/player_edit.php?id=1450

**Comment by myperx** [comment]
Kann den Dump leider irgendwie nicht Hochladen aber eine table wie der Fehler oben beschreibt liegt nicht vor. Jedoch wüsste ich auch nicht, wieso das Webinterface zum bearbeiten von Spielern diese benötigtß

LG

**Comment by Pictureclass** [comment]
Hast du in deiner Datenbank die Tabelle wanted? 
SQL Dump kannst du per Mail schicken an pic (a) pictureclass.de

**Comment by myperx** [comment]
Nein, die Tabelle existiert nicht.

**Comment by Pictureclass** [comment]
Dann ist das dein Problem. In beiden Altis Life Versionen ist die Tabelle vorhanden. Von wann ist deine Version?

**Comment by myperx** [comment]
Gute Frage :dancer:  
Aber wofür wird die Tabelle denn gebraucht?

**Comment by myperx** [comment]
Gut, hab sie jetzt manuell eingefügt klappt nun alles. Dank dir.

**Comment by Pictureclass** [comment]
Die Tabelle wird dazu genutzt, alle Straftaten von Spielern zu speichern.
