### ISSUE TITLE
User-Passwort ändern

### ISSUE THREAD

**Issue by MqAbdul** [Pictureclass/ALTIS-LIFE-CONTROL#23]
Mir ist es nicht möglich das Passwort zu ändern, geschweige denn einen neuen User über das Webinterface anzulegen (Datenbankfehler). Beim Versuch das Passwort zu ändern passiert nichts (keine Fehlermeldung, etc.)        Sonst gute Arbeit =)

**Comment by Pictureclass** [comment]
Kein weiterer Support oder ähnliches.
