### ISSUE TITLE
Weiterleitung von Spieler auf Fahrzeug

### ISSUE THREAD

**Issue by myperx** [Pictureclass/ALTIS-LIFE-CONTROL#3]
Wenn man bei einem Spieler das Fahrzeug bearbeiten möchte, wird man auf: 

/admin/vehicle_detail.php?id=3289

weitergeleitet. Dort kommt dann jedoch ein 404 Not Found Error.

**Comment by Pictureclass** [comment]
Danke, wird beseitigt

**Comment by Pictureclass** [comment]
Lad dir die neue player_edit.php einmal runter und ersetze die alte. Schau ob es dann geht (sollte eigentlich)

**Comment by myperx** [comment]
Ja, funktioniert perfekt. Vielen dank.
