### ISSUE TITLE
Connect failed

### ISSUE THREAD

**Issue by Mangehasse** [Pictureclass/ALTIS-LIFE-CONTROL#4]
Hi.

We have our database at Havoc.
Once we have installed and run start.sql the database and enters the website where we have placed ALC

so we get this error message.

Grateful if we can get a guide if it is at the havoc the fault is in or PHP settings

Warning: mysqli::mysqli(): (HY000/2005): Unknown MySQL server host '000.000.000.000:Port' (0) in /home/c2131/arpgaming.nu/include/login/db_connect.php on line 23
Connect failed: Unknown MySQL server host '000.000.000.000:Port' (0)

IP and port number is not shown correctly in this post. due. sekrites

Best Regars
Mange

**Comment by Pictureclass** [comment]
So MySQL cant find the Server. Conntect your Hoster, if the Server is accessible from other Servers.

**Comment by Mangehasse** [comment]
Hi.

We have now been running it so that you can log in as admin and see player info.
but when you click on the name, you get this error message.
Fehler: Unknown column 'wantedID' in 'where clause'

the next problem is that when creating a new user, then this error message up.
https://gyazo.com/f27837ca131900996c06c7abaf2931b1.

We use us of Altis Life 4.0 as the database.

Grateful for answers
Mange

**Comment by Pictureclass** [comment]
The wanted Table is part of Altis Life 4.4. Use it, or ignore the error. 

For the second Problem, enable Debug in config.php and show full screenshot with URL. Or copy the URL in the Ticket.

Please create an new ticket for the Problems.
